{
 "title": "jaytaala.com",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   },
   {
    "name": "instance_label_regex",
    "query": "\"^.*/(.*)$\""
   }
  ]
 },
 "panels": [
  {
   "title": "Endpoint Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(probe_http_status_code{instance=~\"$target\"}, \"short_instance\", \"$1\", \"instance\", $instance_label_regex)",
     "legendFormat": "{{ short_instance }}"
    }
   ]
  },
  {
   "title": "SSL Cert Expires in...",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "label_replace(probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time(), \"short_instance\", \"$1\", \"instance\", $instance_label_regex)",
     "legendFormat": "{{ short_instance }}"
    }
   ]
  },
  {
   "title": "HTTP Status Codes vs. Time (hover to view endpoint breakdown)",
   "type": "graph",
   "description": "Mouse hover over graph to view endpoint breakdown.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=~\"$target\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "target",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 28 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 28 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  }
 ]
}